Mvc_Codefirst_RazorSyntax/Models/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Mvc_Codefirst_RazorSyntax.Models
{
    public class DatabaseContext : DbContext
    {
        public DatabaseContext() : base("daya")
        {

        }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblcountry> tblcountries { get; set; }
        public DbSet<tblstate> tblstates { get; set; }
    }
}

Mvc_Codefirst_RazorSyntax/Models/tblEmployee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Mvc_Codefirst_RazorSyntax.Models
{
    public class tblEmployee
    {
        [Key]
        public int empid { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public int salary { get; set; }
        public int country { get; set; }

        public int state { get; set; }
    }
}

Mvc_Codefirst_RazorSyntax/Models/tblEmployee1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mvc_Codefirst_RazorSyntax.Models
{
    public class tblEmployee1
    {

        
        public int empid { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public int salary { get; set; }
        public string country { get; set; }

        public string state { get; set; }
    }
}

Mvc_Codefirst_RazorSyntax/Models/tblcountry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Mvc_Codefirst_RazorSyntax.Models
{
    public class tblcountry
    {
        [Key]
        public int cid { get; set; }
        public string cname { get; set; }
    }
}

Mvc_Codefirst_RazorSyntax/Models/tblstate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Mvc_Codefirst_RazorSyntax.Models
{
    public class tblstate
    {
        [Key]
        public int sid { get; set; }
        public int cid { get; set; }

        public string sname { get; set; }
    }
}

Mvc_Codefirst_RazorSyntax/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc_Codefirst_RazorSyntax.Models;

namespace Mvc_Codefirst_RazorSyntax.Controllers
{
   
    public class EmployeeController : Controller
    {
        DatabaseContext _Db = new DatabaseContext();
        public ActionResult AddEmployee(int id=0)
        {
            ViewBag.ctr = _Db.tblcountries.ToList();
            ViewBag.pp = "Save";
            tblEmployee obj = new tblEmployee();
            if (id > 0)
            {
                var data = (from a in _Db.tblEmployees where a.empid==id select a).ToList();
                
                obj.empid = data[0].empid;
                obj.name = data[0].name;
                obj.city = data[0].city;
                obj.salary = data[0].salary;
                obj.country = data[0].country;
                obj.state = data[0].state;
                ViewBag.pp = "Update";
            }
            ViewBag.stt= (from a in _Db.tblstates where a.cid == obj.country select a).ToList();
            return View(obj);
        }


        public ActionResult DeleteEmployee(int id=0)
        {
            var data = _Db.tblEmployees.Find(id);
            _Db.tblEmployees.Remove(data);
            _Db.SaveChanges();
            return RedirectToAction("ShowEmployee");
        }
        public ActionResult ShowEmployee()
        {
            var data = (from a in _Db.tblEmployees 
                        join b in _Db.tblcountries on a.country equals b.cid
                        join c in _Db.tblstates on a.state equals c.sid
                        select new tblEmployee1 {empid=a.empid,name=a.name,city=a.city,salary=a.salary,country=b.cname,state=c.sname } ).ToList();
            return View(data);
        }
        [HttpPost]
        public ActionResult AddEmployee(tblEmployee _emp)
        {
            if (_emp.empid > 0)
            {
                _Db.Entry(_emp).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                _Db.tblEmployees.Add(_emp);
            }
           
            _Db.SaveChanges();
            return RedirectToAction("ShowEmployee");
        }

        public JsonResult StateGet(int A)
        {
            var data = (from a in _Db.tblstates where a.cid==A select a).ToList();
            return Json(data,JsonRequestBehavior.AllowGet);
        }
    }
}

Mvc_Codefirst_RazorSyntax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc_Codefirst_RazorSyntax.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Mvc_Codefirst_RazorSyntax/Views/Employee/AddEmployee.cshtml
@model Mvc_Codefirst_RazorSyntax.Models.tblEmployee
@{
    ViewBag.Title = "AddEmployee";
}

<h2>AddEmployeeHere</h2>

@using (Html.BeginForm("AddEmployee","Employee",FormMethod.Post))
{
<table>
    @Html.HiddenFor(Model => Model.empid)
    <tr>
        <td>Name:</td>
        <td>@Html.TextBoxFor(Model => Model.name)</td>
    </tr>

    <tr>
        <td>City:</td>
        <td>@Html.TextBoxFor(Model => Model.city)</td>
    </tr>

    <tr>
        <td>Salary:</td>
        <td>@Html.TextBoxFor(Model => Model.salary)</td>
    </tr>

    <tr>
        <td>Country:</td>
        <td>@Html.DropDownListFor(Model => Model.country, new SelectList(ViewBag.ctr, "cid", "cname"), "--Select--", new { onchange="BindState()" } )</td>
    </tr>

    <tr>
        <td>State:</td>
        <td>@Html.DropDownListFor(Model => Model.state, new SelectList(ViewBag.stt,"sid","sname"), "--Select--")</td>
    </tr>

    <tr>
        <td></td>
        <td><input type="submit" value="@ViewBag.pp" /></td>
    </tr>
</table>

}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    function BindState() {
        if ($("#empid").val() > 0) {
            $.ajax({
                url: '../StateGet',
                type: 'post',
                data: { A: $("#country").val() },
                success: function (data) {
                    $("#state").empty();
                    $("#state").append($('<option></option>').html("--Select--").val(0));
                    for (var i = 0; i < data.length; i++) {
                        $("#state").append($('<option></option>').html(data[i].sname).val(data[i].sid));
                    }

                },
                error: function () {
                    alert('State not bind !!');
                }

            });
        }
        else {
            $.ajax({
                url: '../Employee/StateGet',
                type: 'post',
                data: { A: $("#country").val() },
                success: function (data) {
                    $("#state").empty();
                    $("#state").append($('<option></option>').html("--Select--").val(0));
                    for (var i = 0; i < data.length; i++) {
                        $("#state").append($('<option></option>').html(data[i].sname).val(data[i].sid));
                    }

                },
                error: function () {
                    alert('State not bind !!');
                }

            });
        }
    }
</script>

Mvc_Codefirst_RazorSyntax/Views/Employee/ShowEmployee.cshtml
@model IEnumerable<Mvc_Codefirst_RazorSyntax.Models.tblEmployee1>
@{
    ViewBag.Title = "ShowEmployee";
}

<h2>---WELCOME TO DAYANAND KUMAR PAGE--</h2>



<table style="background-color:darkkhaki;color:black;width:1000px">
    <tr style="background-color:orangered;color:black;height:30px">
        <th>Employee Id </th>
        <th>Employee Name </th>
        <th>Employee City </th>
        <th>Employee Salary </th>
        <th>Employee Country </th>
        <th>Employee State </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var a in Model) 
    {
<tr>
    <td>@a.empid</td>
    <td>@a.name</td>
    <td>@a.city</td>
    <td>@a.salary</td>
    <td>@a.country</td>
    <td>@a.state</td>
    <td>@Html.ActionLink("Delete", "DeleteEmployee", new { id = a.empid })</td>
    <td>@Html.ActionLink("Edit", "AddEmployee", new { id = a.empid })</td>

</tr>
    }
</table>

Mvc_Codefirst_RazorSyntax/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mvc_Codefirst_RazorSyntax/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mvc_Codefirst_RazorSyntax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Mvc_Codefirst_RazorSyntax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add New Employee", "AddEmployee", "Employee")</li>
                    <li>@Html.ActionLink("List of Employee", "ShowEmployee", "Employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>